#removing the environment variables
ls()
rm(list = ls())
ls()

#setting the working directory
getwd()
setwd("F:/R-Data-Mining/Assignment 2")
getwd()

#loading the package for data manipulation, tidy and visualization  
library(tidyverse)

#installing and loading package for association mining and association visualization
install.packages("arules")
library(arules)
install.packages("arulesViz")
library(arulesViz)

#importing data
marketdata <- read.csv2('exercise_WS2020_data.csv')
marketdata
str(marketdata)

#converting basket as a factor
marketdata$article_group <- factor(marketdata$article_group)
marketdata$article_group

#converting baskets into different kinds of objects
shopping_basket <- split(marketdata$article_group,marketdata$basket_id)
shopping_basket
retail_transactions <- as(shopping_basket, "transactions")
retail_transactions
#summarizing the data
summary(retail_transactions)

#items frequency plot
itemFrequencyPlot(retail_transactions, topN=30, type='absolute')

#using association rules 
rule1 <- apriori(retail_transactions, parameter = list(supp=0.001, conf=0.1))
#sorting rule1 generated by apriori algorithm in decreasing confidence value
rule1 <- sort(rule1, by='confidence', decreasing = TRUE)
summary(rule1)
#inspecting association rules
inspect(rule1)
plot(rule1)

#using association rule with different support and confidence
rule2 <- apriori(retail_transactions, parameter = list(supp=0.002, conf=0.2))
inspect(rule2)
plot(rule2, measure = c("support", "lift"), shading = "confidence")





